### ISSUE TITLE
Add support for a Open source flow

### ISSUE THREAD

**Issue by rodrigomelo9** [INTI-CMNB-FPGA/fpga_helpers#7]
It for sure will include [Yosys](http://www.clifford.at/yosys/). I am not sure if also the [icestorm project](http://www.clifford.at/icestorm/) or [Symbbiflow](https://symbiflow.github.io/).

**Comment by mithro** [comment]
@rodrigomelo9 Feel free to email me at me@mith.ro if you want to understand the best way to add support for SymbiFlow.
